### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by ferrellsl** [aromanro/SolarSystem#4]
The Textures directory and texture files are missing from the repository.

**Comment by aromanro** [comment]
Yes, they are. As described on the blog https://compphys.go.ro/newtonian-gravity/ I didn't provide them because there might be some licensing issues. I provided links on how they can be obtained, though. I'll add the link to README, too.

**Comment by ferrellsl** [comment]
Thanks.  I downloaded all the textures.  I found that the moon textures had to be resized to 1000x500 or the program would exit unexpectedly.  Great work by the way.  I really like the realism.

**Comment by aromanro** [comment]
Yes, that's also specified on the blog and now in the README: 24 bpp and power of 2. Maybe I should check them in the code.
